name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Question1
      id: question1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Question1
        setup-command: testschema1.sql
        command: SELECT patient_name FROM PATIENT WHERE age > 50;
        input: ''
        expected-output: |-
          Ravi Kumar
          Meera Nair
          Suresh Das
        comparison-method: contains
        timeout: 10
        max-score: 10
    - name: Question 1
      id: question-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Question 1
        setup-command: testschema1.sql
        command: SELECT patient_name FROM PATIENT WHERE age > 50;
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        QUESTION1_RESULTS: "${{steps.question1.outputs.result}}"
        QUESTION-1_RESULTS: "${{steps.question-1.outputs.result}}"
      with:
        runners: question1,question-1
